name: "release"

on:
    release:
        types: [published]
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    release:
        name: 🚀 release
        runs-on: ubuntu-latest

        strategy:
            matrix:
                registry-url:
                    - https://registry.npmjs.org
                    - https://npm.pkg.github.com/
                include:
                    - registry-url: https://registry.npmjs.org
                      token: ${{ secrets.NPM_AUTH_TOKEN }}
                    - registry-url: https://npm.pkg.github.com/
                      token: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: 📚 checkout
              uses: actions/checkout@v3
            - name: 🟢 node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: ${{ matrix.registry-url }}
            - name: 🚀 publish
              run: npm publish --access public
              working-directory: Tokenpass
              continue-on-error: true
              env:
                  NODE_AUTH_TOKEN: ${{ matrix.token }}
