name: "release"

on:
    release:
        types: [published]
    workflow_dispatch:

jobs:
    release:
        name: 🚀 release
        runs-on: ubuntu-latest

        strategy:
            matrix:
                registry-url:
                    - https://registry.npmjs.org
                    - https://npm.pkg.github.com/
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v3
            - name: 🟢 node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: ${{ matrix.registry-url }}
            - name: 🚀 publish
              run: npm publish --access public
              working-directory: Tokenpass
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
